rosbag_record:
  ros__parameters:
    # 需要录制的话题列表
    topics:
      - /rm_referee/ground_robot_position
      - /rm_referee/sentry_info

    # bag 输出目录（必须为绝对路径）
    output_dir: /home/nuc/Desktop/SentryNav2026_XDU/src/rosbag_record/bag
    bag_prefix: sentry

    # 当 /rm_referee/game_status.game_progress == 3 开始录制
    start_game_progress: 3
    # 当 /rm_referee/game_status.game_progress == 5 停止录制
    stop_game_progress: 5

    max_cache: 100
    stop_timeout_sec: 5.0
