pub_point_bt_node:
  ros__parameters:
    # ----------------------------------------------------
    # S 型绕桩路径点配置
    # 格式：[x, y, yaw_deg,  x, y, yaw_deg, ...]
    # 注意：必须保留前两行的缩进结构！
    # ----------------------------------------------------
    points: [
      0.5, -0.5, 0.0,   # P1: 第一个点
      1.8,  0.5, 0.0,   # P2: 第二个点
      2.5, -0.5, 0.0,   # P3: 第三个点
      -0.5, 1.5, 0.0    # P4: 只是示例，你可以自己加
    ]