pub_point_bt_node:
  ros__parameters:
    points: [
      2.0, 0.0, 90.0,   # P1: 第一转弯点 (右下，准备左转)
      0.0, 1.0, 90.0,   # P2: 第二转弯点 (左中，准备右转)
      6.0, 2.0, 90.0,   # P3: 第三转弯点 (右中，准备左转)
      0.0, 3.0, 90.0,   # P4: 第四转弯点 (左上，准备右转)
      6.0, 4.0, 0.0     # End: 终点 (右上，直冲终点)
    ]