field_to_odom_tf_node:
  ros__parameters:
    field_frame: rm_field
    odom_frame: odom

    # x / y / z 单位为 m，roll / pitch / yaw 单位为弧度
    # robot_id 7: 红方哨兵机器人
    red:
      field_to_odom_x: 3.725
      field_to_odom_y: 7.5
      field_to_odom_z: 0.0
      field_to_odom_roll: 0.0
      field_to_odom_pitch: 0.0
      field_to_odom_yaw: 0.0

    # robot_id 107: 蓝方哨兵机器人
    blue:
      field_to_odom_x: 24.275
      field_to_odom_y: 7.5
      field_to_odom_z: 0.0
      field_to_odom_roll: 0.0
      field_to_odom_pitch: 0.0
      field_to_odom_yaw: 3.1415926
