field_to_odom_tf_node:
  ros__parameters:
    field_frame: rm_field
    odom_frame: odom

    # 第三个参数单位为弧度
    # robot_id 7: 红方哨兵机器人
    red:
      field_to_odom_x: 0.0
      field_to_odom_y: 0.0
      field_to_odom_yaw: 0.0

    # robot_id 107: 蓝方哨兵机器人
    blue:
      field_to_odom_x: 0.0
      field_to_odom_y: 0.0
      field_to_odom_yaw: 0.0
