<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pri_adaptive_mppi</name>
  <version>0.1.0</version>
  <description>自适应MPPI控制器wrapper，根据路径穿越指定直线的方向自动切换三套MPPI参数</description>
  <license>MIT</license>
  <maintainer email="qza36@outlook.com">ZhiangQi</maintainer>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_core</depend>
  <depend>nav2_util</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>nav2_mppi_controller</depend>
  <depend>pluginlib</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <depend>sentry_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
