can_to_ros:
  # game_progress 发布到 /game_progress 话题
  - cmd_id: 0x0001
    msg_type: MatchStage       
    topic: /game_progress
    field_map:
      data: game_progress

  # stage_remain_time 发布到 /stage_remain_time 话题
  - cmd_id: 0x0001
    msg_type: RemainTime      
    topic: /stage_remain_time
    field_map:
      data: stage_remain_time
